Dev 15107: creating heinemann xml connector
productsupcom/bin-cde-richemont-heinemann pull request #1
Opened 2023-07-14 13:11 UTC by khelmrich

2023-07-21 06:49 UTC, kamil-fityka submitted a review, later dismissed

2023-07-24 11:57 UTC, jacekgadomski requested changes
Mostly minor things, I see some room for improvement regarding xml building and maybe ftp but lets leave it for next round

2023-07-24 11:57 UTC, jacekgadomski commented on app.php
> +        ->getApplication()
csfix

2023-07-24 11:57 UTC, jacekgadomski commented on config/services.yml
> +    xml-header: '<?xml version="1.0" encoding="utf-8"?><n0:ArticleBulkRequest xmlns:n0="http://montblanc.de/xi/ERP/MDM" xmlns:prx="urn:sap.com:proxy:MBP:/1SAI/TAS81A8E819F7B96D2C6D2F:750"></n0:Articl
does it change? if not then it can be moved as a regular constant

2023-07-24 11:57 UTC, jacekgadomski commented on config/services.yml
> +    xml-receiver-id: 'HEINEMANN-API'
same

2023-07-24 11:57 UTC, jacekgadomski commented on config/services.yml
> +#    Productsup\CDE\Connector\Application\Logger\ConnectorLogger:
if you are using services_local.yml this is redundant

2023-07-24 11:57 UTC, jacekgadomski commented on src/Export/Infrastructure/Cli/ExportCommand.php
> +            //'xml-header'=> self::OPTION_XML_HEADER,
pls remove comment

2023-07-24 11:57 UTC, jacekgadomski commented on src/Export/Application/Transfomer/FlattedData.php
> +class FlattedData
it should be `FlattenedData` if it is value object or dto but since it is a service it should be `DataFlattener`, remember to change test name accordingly

2023-07-24 11:57 UTC, jacekgadomski commented on src/Export/Application/XML/Builder/XmlDataNode.php
> +final class XmlDataNode
I would change the name to `XmlDataNodeBuilder`

2023-07-24 11:57 UTC, jacekgadomski commented on src/Export/Application/XML/Parser/Article.php
> +final class Article
I would change the name to `ArticleNodeBuilder`, wdyt?

2023-07-24 11:57 UTC, jacekgadomski commented on src/Export/Application/XML/Parser/ArticleHierarchy.php
> +final class ArticleHierarchy
I would change the name to `ArticleHierarchyNodeBuilder`, wdyt?

2023-07-24 11:57 UTC, jacekgadomski commented on src/Export/Infrastructure/Upload/Adapter/AdapterFactory.php
> +    public function make(): FtpUploader|SftpUploader
please introduce interface `Uploader` (`FtpUploader` and `SftpUploader` should implement it) and replace `FtpUploader|SftpUploader` with `Uploader`

2023-07-24 11:57 UTC, jacekgadomski commented on src/Export/Infrastructure/Provider/ConfigProviderInterface.php
> +    public function getRemoteFile(): string;
I think you do need this interface

2023-07-24 11:57 UTC, jacekgadomski commented on src/Export/Application/XML/Parser/Receiver.php
> +final class Receiver
I would change the name to `ReceiverNodeBuilder`

2023-07-24 11:57 UTC, jacekgadomski commented on src/Export/Infrastructure/Service/ExportService.php
> +            $this->exceptionHandler->handle($e);
i would move this exception handling to place where certain exceptions is can be thrown, for other exception we have general exception handler

2023-07-25 06:09 UTC, khelmrich commented on tests/config/services.yml
> +
done

2023-07-25 06:09 UTC, khelmrich commented on tests/Unit/SftpAdapterFactoryTest.php
> +{
ok got it

2023-07-25 06:09 UTC, khelmrich commented on tests/Unit/FtpAdapterFactoryTest.php
> +        $factory = FtpAdapterFactory::make();
ok got it

2023-07-25 06:09 UTC, khelmrich commented on tests/Unit/ConfigurationTest.php
> +        $config = new Configuration(
ok got it

2023-07-25 06:09 UTC, khelmrich commented on tests/Unit/ConfigProviderTest.php
> +        $this->configProvider = new ConfigProvider(self::REMOTE_FILE, self::FEED_NAME, self::FTP_HOST, self::FTP_DIRECTORY);
ok got it

2023-07-25 06:10 UTC, khelmrich commented on src/Export/Application/XML/Parser/ArticleHierarchy.php
> +final class ArticleHierarchy
done

2023-07-25 06:10 UTC, khelmrich commented on src/Export/Infrastructure/Upload/Adapter/AdapterFactory.php
> +    public function make(): FtpUploader|SftpUploader
done

2023-07-25 06:10 UTC, khelmrich commented on src/Export/Infrastructure/Provider/ConfigProviderInterface.php
> +    public function getRemoteFile(): string;
removed

2023-07-25 06:15 UTC, khelmrich commented on src/Export/Application/XML/Parser/Receiver.php
> +final class Receiver
renamed

2023-07-25 06:15 UTC, khelmrich commented on src/Export/Infrastructure/Service/ExportService.php
> +            $this->exceptionHandler->handle($e);
changed

2023-07-25 06:16 UTC, khelmrich commented on tests/Unit/AdapterFactoryTest.php
> +        $this->ftpMock = $this->createMock(Ftp::class);
ok, got it

2023-07-25 06:16 UTC, khelmrich commented on src/Export/Infrastructure/Upload/Exception/UploadException.php
> +    public static function failedUpload(string $filename, string $host, int $port, ?Throwable $previous = null): self
done

2023-07-25 06:16 UTC, khelmrich commented on src/Export/Infrastructure/Cli/ExportCommand.php
> +//            ->addOption(
done

2023-07-25 06:16 UTC, khelmrich commented on src/Export/Infrastructure/Cli/ExportCommand.php
> +    //private const OPTION_XML_HEADER = 'xml-header';
done

2023-07-25 06:18 UTC, khelmrich commented on app.php
> +        ->getApplication()
done

2023-07-25 06:18 UTC, khelmrich commented on config/services.yml
> +    xml-header: '<?xml version="1.0" encoding="utf-8"?><n0:ArticleBulkRequest xmlns:n0="http://montblanc.de/xi/ERP/MDM" xmlns:prx="urn:sap.com:proxy:MBP:/1SAI/TAS81A8E819F7B96D2C6D2F:750"></n0:Articl
not need, deleted

2023-07-25 06:20 UTC, khelmrich commented on config/services.yml
> +    xml-receiver-id: 'HEINEMANN-API'
this is one of command options, which can be edited by customer and this is default value

2023-07-25 06:21 UTC, khelmrich commented on config/services.yml
> +#    Productsup\CDE\Connector\Application\Logger\ConnectorLogger:
removed

2023-07-25 06:21 UTC, khelmrich commented on src/Export/Infrastructure/Cli/ExportCommand.php
> +            //'xml-header'=> self::OPTION_XML_HEADER,
removed

2023-07-25 06:21 UTC, khelmrich commented on src/Export/Application/Transfomer/FlattedData.php
> +class FlattedData
changed

2023-07-25 06:21 UTC, khelmrich commented on src/Export/Application/XML/Builder/XmlDataNode.php
> +final class XmlDataNode
changed

2023-07-25 06:21 UTC, khelmrich commented on src/Export/Application/XML/Parser/Article.php
> +final class Article
right, done

2023-08-01 10:39 UTC, jacekgadomski approved these changes

2023-08-01 13:28 UTC, kamil-fityka approved these changes

2023-08-02 06:49 UTC, merged